//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsCategoryBrand
    {
        public int Id { get; set; }
        public int Product { get; set; }
        public string Category { get; set; }
        public string Brand { get; set; }
    
        public virtual Brand Brand1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Products Products { get; set; }
    }
}
