//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.BillDetail = new HashSet<BillDetail>();
            this.ProductsCategoryBrand = new HashSet<ProductsCategoryBrand>();
            this.ProductSuppliers = new HashSet<ProductSuppliers>();
            this.WarehouseProducts = new HashSet<WarehouseProducts>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string CostPrice { get; set; }
    
        public virtual ICollection<BillDetail> BillDetail { get; set; }
        public virtual ICollection<ProductsCategoryBrand> ProductsCategoryBrand { get; set; }
        public virtual ICollection<ProductSuppliers> ProductSuppliers { get; set; }
        public virtual ICollection<WarehouseProducts> WarehouseProducts { get; set; }
    }
}
