//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public Warehouse()
        {
            this.WarehouseProducts = new HashSet<WarehouseProducts>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<WarehouseProducts> WarehouseProducts { get; set; }
    }
}
